openapi: 3.0.0
info:
  title: Homepage
  version: 0.0.1
tags:
  - name: homepage
    description: Data for display on the main page
paths:
  /homepage:
    get:
      tags:
        - homepage
      summary: Get homepage data
      description: Data displayed on the main
      parameters:
        - in: query
          name: language
          description: Data to obtain a content group
          schema:  
            $ref: "api-doc.yaml#/components/schemas/Language"
      responses:
        200: 
          description: Request completed successfully
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/HomePageResponse'
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        500:
          $ref: 'api-doc.yaml#/components/responses/5XX'
      
    post:
      tags:
        - homepage
      summary: Set homepage data
      description: Setting the fields for the main page
      security:
        - BearerAuth: []
      requestBody:
        description: Query body for data change
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HomePageRequest'
      responses:
        200:
          description: OK. Data saved 
          content: 
            application/json:
              schema:
                type: object
                properties:
                  language:
                    type: string
                  message:
                    type: string
                example:
                  language: 'en'
                  message: Data for home page successful saved
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        401:
          $ref: 'api-doc.yaml#/components/responses/UnauthorizedError'
        500:
          $ref: 'api-doc.yaml#/components/responses/5XX'
    
    put:
      tags:
        - homepage
      description: Update the data for the home page
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HomePageRequest'
      responses:
        200:
          description: OK. Data Update 
          content: 
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
                example:
                  id: 3
                  message: Data for home page successful updated
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        401:
          $ref: 'api-doc.yaml#/components/responses/UnauthorizedError'
        500:
          $ref: 'api-doc.yaml#/components/responses/5XX'
 
components:
  schemas:
    HomePageBase: 
      type: object
      properties:
        title: 
          type: string
          readOnly: true
        subtitle: 
          type: string
          readOnly: true
        description:
          type: string
          readOnly: true
      example:
            title: Text for title main page
            subtitle: Text for subtitle main page
            description: text description for main page
    HomePageRequest:
      allOf:
        - type: object
          properties:
            title: 
              $ref: "api-doc.yaml#/components/schemas/StringWithDivisionIntoLanguages"
            subtitle: 
              $ref: "api-doc.yaml#/components/schemas/StringWithDivisionIntoLanguages"
            description:
              $ref: "api-doc.yaml#/components/schemas/StringWithDivisionIntoLanguages"
          example:
            title: {
              en: 'text in English',
              ru: 'На русском',
            }
            subtitle: {
              en: 'text in English',
              ru: 'На русском',
            }
            description: {
              en: 'text in English',
              ru: 'На русском',
            }
        - type: object
          properties:
            avatars:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  imageId:  
                    type: string
          example:
            avatars: [
              {
                type: 'black',
                imageId: 9,
              }
            ]
    HomePageResponse:
      allOf:
        - type: object
          properties:
            currentLanguage:
              $ref: "api-doc.yaml#/components/schemas/Language"
            languages:
              type: array
              items:
                $ref: "api-doc.yaml#/components/schemas/Language"
          example:
            currentLanguage: 'en'
            languages: [ 'ru', 'en' ]
        - $ref: '#/components/schemas/HomePageBase'
        - type: object
          properties:
            avatars:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  images:
                    type: array
                    items: 
                      type: object
                      properties:
                        id: 
                          type: string
                        name: 
                          type: string
                        description:
                          type: string
                        templateName: 
                          type: string
                        width: 
                          type: number
                        height:
                          type: number
                        url: 
                          type: string
                      required:
                        - url
          example:
            avatars:  [ 
              { 
                type: black,
                images: [
                  {
                    id: 'xxxxxx',
                    name: 'pic-500x500-mid.png',
                    description: 'Photo is my when I was young',
                    templateName: 'original', 
                    width: 500, 
                    height: 500, 
                    url: 'public/images/pic-500x500-mid.png', 
                  }
                ]
              }
            ] 
            
