openapi: 3.0.0
info:
  title: Social media
  version: 0.0.1
tags:
  - name: social-media
    description: Management of links for communication with the site owner
paths:
  /social-media:
    get:
      tags:
        - social-media
      description: Get list social media entities
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/SocialMediaView'
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        500: 
          $ref: 'api-doc.yaml#/components/responses/5XX'    
    post: 
      tags:
        - social-media
      description: Create new link social media
      requestBody:
        description: Data for new link
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/SocialMediaCreation'
      responses:
        200:
          $ref: 'api-doc.yaml#/components/responses/200AfterSuccessfulChangesEntity'  
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        500: 
          $ref: 'api-doc.yaml#/components/responses/5XX' 
  /social-media/{id}:
    put: 
      tags:
        - social-media
      description: Change one the social media
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: desc 
      requestBody:
        description: New Data for social media
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/SocialMediaCreation'
      responses:
        200:
          $ref: 'api-doc.yaml#/components/responses/200AfterSuccessfulChangesEntity'
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        500: 
          $ref: 'api-doc.yaml#/components/responses/5XX'    
    delete:
      tags:
        - social-media
      description: Delete one of Social media
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: desc 
      responses:
        200:
          $ref: 'api-doc.yaml#/components/responses/200AfterSuccessfulChangesEntity'
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        500: 
          $ref: 'api-doc.yaml#/components/responses/5XX'       
 
components:
  schemas:
    SocialMediaCommon:
      type: object
      required:
        - link
        - name
      properties:
        name: 
          type: string
          example: Github
        link:
          type: string
          example: http://github.com/user.git
    SocialMediaCreation: 
      allOf:
        - $ref: '#/components/schemas/SocialMediaCommon'
        - type: object
          properties:
            imageId: 
              type: string
              example: ddfdzrn1dw
    
    SocialMediaView:
      allOf:
        - $ref: '#/components/schemas/SocialMediaCommon'
        - type: object
          properties:
            id: 
              type: string
              example: 10
            icon:
              $ref: 'image.yaml#/components/schemas/Icon'
        
    