openapi: 3.0.0
info:
  title: Time-stamps
  version: 0.0.1
tags:
  - name: time-stamps
    description: Career history
paths:
  /time-stamps:
    get:
      tags:
        - time-stamps
      parameters:
        - in: query
          name: language
          schema:
            $ref: 'api-doc.yaml#/components/schemas/Language'
              
      responses:
        200:
          description: Received a list of time points successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  languages: 
                    $ref: 'api-doc.yaml#/components/schemas/Languages'
                  currentLanguage: 
                    $ref: 'api-doc.yaml#/components/schemas/Language'
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/TimeStampsView'

        400: 
          $ref: 'api-doc.yaml#/components/responses/4XX'
        500:
          $ref: 'api-doc.yaml#/components/responses/5XX'
    post: 
      tags:
        - time-stamps
      description: Create a time stamp
      security:
        - BearerAuth: []
      requestBody:
        description: Time label fields
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/TimeStampsCreation'
      responses:
        200:
          $ref: 'api-doc.yaml#/components/responses/200AfterSuccessfulChangesEntity'
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        401:
          $ref: 'api-doc.yaml#/components/responses/UnauthorizedError'
        500: 
          $ref: 'api-doc.yaml#/components/responses/5XX'
  /time-stamp/{id}:
    get:
      tags:
        - time-stamps
      description: Get one time stamps
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: desc 
        - in: query
          name: language
          schema:
            $ref: 'api-doc.yaml#/components/schemas/Language'
      responses:
        200:
          description: Successfully received the data on the time stamp
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      currentLanguage:
                        $ref: 'api-doc.yaml#/components/schemas/Language'
                  - $ref: '#/components/schemas/TimeStampsView'
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        500: 
          $ref: 'api-doc.yaml#/components/responses/5XX'
    put: 
      tags:
        - time-stamps
      description: Change one the Time stamp
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Id Time stamp for changing 
      requestBody:
        description: New Data for Time stamp
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/TimeStampsCreation'
      responses:
        200:
          $ref: 'api-doc.yaml#/components/responses/200AfterSuccessfulChangesEntity'
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        401:
          $ref: 'api-doc.yaml#/components/responses/UnauthorizedError'
        500: 
          $ref: 'api-doc.yaml#/components/responses/5XX'    
    delete:
      tags:
        - time-stamps
      description: Delete one of Time stamp
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: desc 
      responses:
        200:
          $ref: 'api-doc.yaml#/components/responses/200AfterSuccessfulChangesEntity'
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        401:
          $ref: 'api-doc.yaml#/components/responses/UnauthorizedError'
        500: 
          $ref: 'api-doc.yaml#/components/responses/5XX'    

components:
  schemas:
    TimeStampsCommon:
      type: object
      properties:
        name:
          type: string
          example: Компания ООО Петрушка
        link: 
          type: string
          example: http://example.com
        events:
          $ref: 'api-doc.yaml#/components/schemas/Events'
    
    TimeStampsView:
      allOf:
        - $ref: '#/components/schemas/TimeStampsCommon'
        - type: object
          properties:
            id:
              type: string
              example: 10
            description:
              type: string
              example: text about job
    
    TimeStampsCreation:
      allOf:
        - $ref: '#/components/schemas/TimeStampsCommon'
        - type: object
          properties:
            description:
              $ref: 'api-doc.yaml#/components/schemas/StringWithDivisionIntoLanguages'
      


