openapi: 3.0.0
info:
  title: Skills
  version: 0.0.1
tags:
  - name: skills
    description: Skills which has the site owner

paths:
  /skills:
    get:
      tags:
        - skills
      description: Get a list of skills
      parameters:
        - in: query
          name: page 
          schema: 
            type: number
          example: 2
        - in: query
          name: pageSize
          schema:
            type: number
          example: 10
        - in: query
          name: sort
          schema:
            $ref: 'api-doc.yaml#/components/schemas/Sort'
        - in: query
          name: language
          schema:
            $ref: 'api-doc.yaml#/components/schemas/Language'
      responses:
        200:
          description: successfully received a list of skills
          content:
            application/json:
              schema:
                type: object
                required:
                  - items
                properties:
                  pagination:
                    $ref: 'api-doc.yaml#/components/schemas/PaginationInResponse'
                  sorted:
                    type: string
                    example: '+name,-group'
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/SkillView'
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        500:
          $ref: 'api-doc.yaml#/components/responses/5XX'
    post: 
      tags:
        - skills  
      description: Creating a new skill
      requestBody:
        description: Structure of new experience
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/SkillCreation'
      responses:
        200:
          $ref: 'api-doc.yaml#/components/responses/200AfterSuccessfulChangesEntity'
        400: 
          $ref: 'api-doc.yaml#/components/responses/4XX'
        500:
          $ref: 'api-doc.yaml#/components/responses/5XX'
 
  /skills/{id}:
    get:
      tags:
        - skills
      description: Get one entities skill by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: desc 
        - in: query
          name: language
          schema:
            $ref: 'api-doc.yaml#/components/schemas/Language'
      responses:
        200:
          description: Object experience received successfully 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SkillView'                 
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        500:
          $ref: 'api-doc.yaml#/components/responses/5XX'
    put:
      tags:
        - skills
      description: Change one entities skill by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: desc 
      requestBody:
        description: Modified object experience
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/SkillCreation'
      responses:
        200:
          $ref: 'api-doc.yaml#/components/responses/200AfterSuccessfulChangesEntity'
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        500:
          $ref: 'api-doc.yaml#/components/responses/5XX'
    delete:
      tags:
        - skills
      description: Delete one entities skill by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: desc 
      responses:
        200:
          $ref: 'api-doc.yaml#/components/responses/200AfterSuccessfulChangesEntity'
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        500:
          $ref: 'api-doc.yaml#/components/responses/5XX'

 
  
components:
  schemas:
    SkillCommon:
      type: object
      properties:
        name: 
          type: string
          example: JavaScript
        group: 
          type: string
          example: language
        icon:
          type: string
          format: binary
          example: TWFuIGlzIGRpc3Rpbmd1aXNoZWQsIG5vdCB...
        level:
          type: number
          maximum: 10
          minimum: 0
          example: 5
      required:
        - name


    SkillCreation:
      allOf:
        - $ref: '#/components/schemas/SkillCommon'
        - type: object
          properties:
            description:
              $ref: 'api-doc.yaml#/components/schemas/StringWithDivisionIntoLanguages'

            
    SkillView:
      allOf:
        - $ref: '#/components/schemas/SkillCommon'
        - type: object
          properties:
            id:
              type: string
              example: 10
            languages: 
              $ref: 'api-doc.yaml#/components/schemas/Languages'
            currentLanguage: 
              $ref: 'api-doc.yaml#/components/schemas/Language'
            description:
              type: string
              example: text about this skill 
        
     