openapi: 3.0.0
info:
  title: Callback
  version: 0.0.1
tags:
  - name: callback
    description: Working with feedback form
    
paths:
  /callback:
    post:
      tags:
        - callback
      description: Send callback form 
      security:
        - BearerAuth: []
      requestBody:
        description: Structure of new experience
        content:
          application/json:
            schema: 
              type: object
              properties:
                email:
                  type: string
                  example: mymail@mail.com
                message:
                  type: string
                  example: Hello, I want you offer interesting idea about ...
              required:
                - email
                - message
      responses:
        200:
          description: Message is received
          
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Your message is received and nearest time I answer you
                required:
                  - message
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        500:
          $ref: 'api-doc.yaml#/components/responses/5XX'
