openapi: 3.0.0
info:
  title: Homepage
  version: 0.0.1
tags:
  - name: homepage
    description: Data for display on the main page
paths:
  /homepage/multilingual:
    get: 
      tags:
        - homepage
      summary: Getting data about home page in all supported languages
      description: Getting data about home page in all supported languages
      responses:
        200:
          description: Request completed successfully
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/HomePageMultilingual'
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        500:
          $ref: 'api-doc.yaml#/components/responses/5XX'
  /homepage:
    get:
      tags:
        - homepage
      summary: Get homepage data
      description: Data displayed on the main
      parameters:
        - in: query
          name: language
          description: Data to obtain a content group
          schema:  
            $ref: 'api-doc.yaml#/components/schemas/Language'
      responses:
        200: 
          description: Request completed successfully
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/HomePageView'
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        500:
          $ref: 'api-doc.yaml#/components/responses/5XX'
      
    post:
      tags:
        - homepage
      summary: Set homepage data
      description: Setting the fields for the main page
      security:
        - BearerAuth: []
      requestBody:
        description: Query body for data change
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HomePageCreation'
      responses:
        200:
          description: OK. Data saved 
          content: 
            application/json:
              schema:
                type: object
                properties:
                  language:
                    type: string
                  message:
                    type: string
                example:
                  language: 'en'
                  message: Data for home page successful saved
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        401:
          $ref: 'api-doc.yaml#/components/responses/UnauthorizedError'
        500:
          $ref: 'api-doc.yaml#/components/responses/5XX'
    
    put:
      tags:
        - homepage
      description: Update the data for the home page
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HomePageCreation'
      responses:
        200:
          $ref: 'api-doc.yaml#/components/responses/200AfterSuccessfulChangesEntity'
        400:
          $ref: 'api-doc.yaml#/components/responses/4XX'
        401:
          $ref: 'api-doc.yaml#/components/responses/UnauthorizedError'
        500:
          $ref: 'api-doc.yaml#/components/responses/5XX'
 
components:
  schemas:
    AvatarCreation: 
      type: object
      properties:
        type:
          type: string
          example: black
        imageId:  
          type: string
          example: 9
    
    AvatarView:
      type: object
      properties:
        type: 
          type: string
          example: black
        image: 
          $ref: 'image.yaml#/components/schemas/Image'
    
    ObjectWithLanguages:
      $ref: 'api-doc.yaml#/components/schemas/StringWithDivisionIntoLanguages'

    HomePageCreation:
      allOf:
        - type: object
          properties:
            title: 
              $ref: '#/components/schemas/ObjectWithLanguages'
            subtitle: 
              $ref: '#/components/schemas/ObjectWithLanguages'
            description:
              $ref: '#/components/schemas/ObjectWithLanguages'
            avatars:
              type: array
              items:
                $ref: '#/components/schemas/AvatarCreation'
    
    HomePageView:
      allOf:
        - type: object
          properties:
            currentLanguage:
              $ref: 'api-doc.yaml#/components/schemas/Language'
            languages:
              type: array
              items:
                $ref: 'api-doc.yaml#/components/schemas/Languages'
            title: 
              type: string
              readOnly: true
              example: Text for title main page
            subtitle: 
              type: string
              readOnly: true
              example: Text for subtitle main page
            description:
              type: string
              readOnly: true
              example: text description for main page
        - type: object
          properties:
            avatars:
              type: array
              items:
                $ref: '#/components/schemas/AvatarView'

    HomePageMultilingual: 
      allOf:
        - type: object
          properties:
            languages:
              type: array
              items:
                $ref: 'api-doc.yaml#/components/schemas/Languages'
            title: 
              $ref: '#/components/schemas/ObjectWithLanguages'
            subtitle: 
              $ref: '#/components/schemas/ObjectWithLanguages'
            description:
              $ref: '#/components/schemas/ObjectWithLanguages'
        - type: object
          properties:
            avatars:
              type: array
              items:
                $ref: '#/components/schemas/AvatarView'
          
            
